import { TabMap } from "@/app/types/tabmap";

export const tabMap: TabMap = {
  web开发模版: "web-development-template",
  图片视频处理工具: "image-and-video-processing-tools",
  Logo: "logo",
  UI模版和组件: "ui-templates-and-components",
  错误跟踪: "error-tracking",
  支付: "payment",
  Idea: "idea",
  信息渠道: "information-channels",
  样式与UI: "styles-and-ui",
  ORM: "orm",
  在线客服: "online-customer-service",
  网站分析: "website-analytics",
  邮件: "email",
  登陆鉴权: "authentication",
  数据库: "database",
  后端: "backend",
  前端: "frontend",
  Chrome插件开发模板: "chrome-extension-development-template",
  域名购买: "domain-registration",
  文档管理: "document-management",
  图标库: "icon-library",
  短链: "short-links",
  原型设计: "prototype-design",
  图片视频素材: "image-and-video-assets",
  录屏: "screen-recording",
  部署与托管: "deployment-and-hosting",
  协议生成: "protocol-generation",
};
